# Generated by Django 3.2.3 on 2021-05-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_player_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
