# Generated by Django 3.2.3 on 2021-08-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="metric",
            old_name="metric_type",
            new_name="type",
        ),
    ]
