# Generated by Django 3.2.3 on 2021-08-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_rename_metric_type_metric_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="metric",
            old_name="type",
            new_name="group",
        ),
    ]
